name: Tests
on:
  pull_request
  push:
    branches:
      - develop
      - master
jobs:
  actions:
    runs-on: ubuntu-latest
    steps:
    - name: Copia repositorio
      uses: actions/checkout@v2
    - name: Construye imagen
      run: docker build --tag islasgeci/common_task_framework .
    - name: Verifica el formato
      run: docker run islasgeci/common_task_framework make check
    - name: Corre pruebas y evalúa cobertura
      run: docker run islasgeci/common_task_framework make coverage
    - name: Evalúa resistencia a mutaciones
      run: docker run islasgeci/common_task_framework make mutants
