name: Tests
on:
  push:
    branches:
      - develop
jobs:
  actions:
    runs-on: ubuntu-latest
    steps:
    - name: Copia repositorio
      uses: actions/checkout@v2
    - name: Construye imagen
      run: docker build --tag islasgeci/common_task_framework:latest .
    - name: Verifica el formato
      run: docker run islasgeci/common_task_framework:latest make check
    - name: Corre pruebas
      run: docker run islasgeci/common_task_framework:latest make init
    - name: Evalúa resistencia a mutaciones
      run: docker run islasgeci/common_task_framework:latest make mutants
